version: '3'

services:
  agrilink_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: agrilinknginx
    ports:
      - "8186:8186"
    depends_on:
      - agrilink_app
    